export const STATUS_BAD_REQUEST = 400;
export const STATUS_NOT_FOUND = 404;

export const INVALID_PRODUCT_ID = "INVALID_PRODUCT_ID";
export const INVALID_OPTION_ID = "INVALID_OPTION_ID";
export const INVALID_UNIT_ID = "INVALID_UNIT_ID";
export const INVALID_AVAILABILITY_ID = "INVALID_AVAILABILITY_ID";
export const INVALID_BOOKING_UUID = "INVALID_BOOKING_UUID";
export const BAD_REQUEST = "BAD_REQUEST";
export const UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY";
export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const FORBIDDEN = "FORBIDDEN";
export const NOT_FOUND = "NOT_FOUND";
